alter table EDYCJA add PRZEDMIOT_ID INT;
alter table EDYCJA add FOREIGN KEY (PRZEDMIOT_ID) REFERENCES PRZEDMIOT(ID);

alter table GRUPA add EDYCJA_ID INT;
alter table GRUPA add FOREIGN KEY (EDYCJA_ID) REFERENCES EDYCJA(ID);

alter table UCZESTNIK add GRUPA_ID INT;
alter table UCZESTNIK add FOREIGN KEY (GRUPA_ID) REFERENCES GRUPA(ID);