create table PRZEDMIOT(
    ID int NOT NULL AUTO_INCREMENT,
    NAZWA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

create table EDYCJA(
    ID int NOT NULL AUTO_INCREMENT,
    NAZWA VARCHAR(255) NOT NULL,
    ROCZNIK INT NOT NULL,
    PRIMARY KEY (ID)
);

create table GRUPA(
    ID int NOT NULL AUTO_INCREMENT,
    NAZWA VARCHAR(255) NOT NULL,
    NUMER_GRUPY NUMERIC(2) NOT NULL,
    PRIMARY KEY (ID)
);

create table UCZESTNIK(
    ID int NOT NULL AUTO_INCREMENT,
    IMIE VARCHAR(255) NOT NULL,
    NAZWISKO VARCHAR(255) NOT NULL,
    NUMER_ALBUMU NUMERIC(6) NOT NULL,
    PRIMARY KEY (ID)
);

create table SZABLONY(
    ID int NOT NULL AUTO_INCREMENT,
    UCZESTNIK_ID INT,
    GRUPA_ID INT,
    EDYCJA_ID INT,
    NAZWA VARCHAR(255) NOT NULL,
    TRESC VARCHAR(255) NOT NULL,
    FOREIGN KEY (UCZESTNIK_ID) REFERENCES UCZESTNIK(ID),
    FOREIGN KEY (GRUPA_ID) REFERENCES GRUPA(ID),    
    FOREIGN KEY (EDYCJA_ID) REFERENCES EDYCJA(ID),    
    PRIMARY KEY (ID)
);


