INSERT INTO PRZEDMIOT (NAZWA)
values('SSBD');

INSERT INTO EDYCJA (NAZWA, ROCZNIK)
values('Edycja Pierwsza', 2017);

INSERT INTO GRUPA (NAZWA, NUMER_GRUPY)
values('Testowa', 01);

INSERT INTO UCZESTNIK(IMIE, NAZWISKO, NUMER_ALBUMU)
values('Jan','Kowalski', 123456);


INSERT INTO SZABLONY (UCZESTNIK_ID, GRUPA_ID, EDYCJA_ID,NAZWA, TRESC)
values(1,1,1,'test','echo test');
