INSERT INTO PRZEDMIOT (NAZWA, OPIS)
values('SSBD', "Wpis testowy");

INSERT INTO EDYCJA (NAZWA, OPIS, PRZEDMIOT_ID)
values('Edycja 1', "Wpis testowy", 2);

INSERT INTO GRUPA (NAZWA, OPIS, EDYCJA_ID)
values('Grupa 1', "Wpis testowy", 3);

INSERT INTO UCZESTNIK(OPIS, LOGIN, GRUPA_ID)
values('Wpis testowy','198955', 4);


INSERT INTO SZABLONY (UCZESTNIK_ID, GRUPA_ID, EDYCJA_ID,PRZEDMIOT_ID, NAZWA, TRESC)
values(2,4,3,2, 'test','echo test');